// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrackHub.TripManagement.Infrastructure.TripDB;

#nullable disable

namespace TrackHub.TripManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260803235450_AddZeroTouchLifecycle")]
    partial class AddZeroTouchLifecycle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrackHub.TripManagement.Infrastructure.TripDB.Entities.Account", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.HasKey("AccountId");

                    b.ToTable("accounts", "app", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("TrackHub.TripManagement.Infrastructure.TripDB.Entities.AccountFeature", b =>
                {
                    b.Property<Guid>("AccountFeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<string>("ConfigurationJson")
                        .HasColumnType("text")
                        .HasColumnName("configurationjson");

                    b.Property<DateTimeOffset?>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effectivefrom");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effectiveto");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("FeatureKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("featurekey");

                    b.HasKey("AccountFeatureId");

                    b.HasIndex("AccountId", "FeatureKey");

                    b.ToTable("account_features", "app", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("TrackHub.TripManagement.Infrastructure.TripDB.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("AuditEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("action");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actorid");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actortype");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correlationid");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ipaddress");

                    b.Property<string>("NewValuesJson")
                        .HasColumnType("text")
                        .HasColumnName("newvaluesjson");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurredat");

                    b.Property<string>("OldValuesJson")
                        .HasColumnType("text")
                        .HasColumnName("oldvaluesjson");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("resourceid");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("resourcetype");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("result");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("useragent");

                    b.HasKey("AuditEventId");

                    b.ToTable("audit_events", "app", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("TrackHub.TripManagement.Infrastructure.TripDB.Entities.Delivery", b =>
                {
                    b.Property<Guid>("DeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<string>("BranchName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("branchname");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("clientname");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Observations")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observations");

                    b.Property<string>("ProductsSummary")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("productssummary");

                    b.Property<string>("Reference")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("reference");

                    b.Property<int>("SequenceIndex")
                        .HasColumnType("integer")
                        .HasColumnName("sequenceindex");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid>("TripStopId")
                        .HasColumnType("uuid")
                        .HasColumnName("tripstopid");

                    b.HasKey("DeliveryId");

                    b.HasIndex("TripStopId");

                    b.HasIndex("AccountId", "TripStopId")
                        .HasDatabaseName("ix_trip_deliveries_accountid_tripstopid");

                    b.ToTable("trip_deliveries", "trip");
                });

            modelBuilder.Entity("TrackHub.TripManagement.Infrastructure.TripDB.Entities.Driver", b =>
                {
                    b.Property<Guid>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("DriverId");

                    b.ToTable("drivers", "app", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("TrackHub.TripManagement.Infrastructure.TripDB.Entities.Geofence", b =>
                {
                    b.Property<Guid>("GeofenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<Point>("CircleCenter")
                        .HasColumnType("geometry (Point, 4326)")
                        .HasColumnName("circlecenter");

                    b.Property<Polygon>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry (Polygon, 4326)")
                        .HasColumnName("geom");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("GeofenceId");

                    b.ToTable("geofences", "geofencing", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("TrackHub.TripManagement.Infrastructure.TripDB.Entities.GeofenceVisit", b =>
                {
                    b.Property<Guid>("GeofenceVisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<DateTimeOffset?>("DepartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("departuretimestamp");

                    b.Property<DateTimeOffset>("EnteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datetime");

                    b.Property<Guid>("GeofenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("geofenceid");

                    b.Property<Guid>("TransporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("transporterid");

                    b.HasKey("GeofenceVisitId");

                    b.ToTable("geofenceevents", "geofencing", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("TrackHub.TripManagement.Infrastructure.TripDB.Entities.PointOfInterest", b =>
                {
                    b.Property<Guid>("PointOfInterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("PointOfInterestId");

                    b.ToTable("points_of_interest", "map", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("TrackHub.TripManagement.Infrastructure.TripDB.Entities.ProofOfDelivery", b =>
                {
                    b.Property<Guid>("ProofOfDeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("capturedat");

                    b.Property<Guid>("ClientEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("clienteventid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("DeliveryId")
                        .HasColumnType("uuid")
                        .HasColumnName("deliveryid");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("ReceiverDocument")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("receiverdocument");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("receivername");

                    b.Property<Guid>("TripStopId")
                        .HasColumnType("uuid")
                        .HasColumnName("tripstopid");

                    b.HasKey("ProofOfDeliveryId");

                    b.HasIndex("TripStopId", "ClientEventId")
                        .IsUnique()
                        .HasDatabaseName("ux_trip_pods_tripstopid_clienteventid");

                    b.ToTable("trip_pods", "trip");
                });

            modelBuilder.Entity("TrackHub.TripManagement.Infrastructure.TripDB.Entities.RoutePlan", b =>
                {
                    b.Property<Guid>("RoutePlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computedat");

                    b.Property<Polygon>("CorridorGeom")
                        .HasColumnType("geometry (Polygon, 4326)")
                        .HasColumnName("corridorgeom");

                    b.Property<int>("CorridorMeters")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(500)
                        .HasColumnName("corridormeters");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("errorcode");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("errormessage");

                    b.Property<decimal?>("EstimatedTollAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("estimatedtollamount");

                    b.Property<LineString>("Geom")
                        .HasColumnType("geometry (LineString, 4326)")
                        .HasColumnName("geom");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("LegsJson")
                        .HasColumnType("text")
                        .HasColumnName("legsjson");

                    b.Property<double>("PlannedDistanceMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("planneddistancemeters");

                    b.Property<int>("PlannedDurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("planneddurationseconds");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("provider");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("TollCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("tollcurrency");

                    b.Property<string>("TollStationsJson")
                        .HasColumnType("text")
                        .HasColumnName("tollstationsjson");

                    b.Property<string>("TollStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tollstatus");

                    b.Property<string>("TollVehicleClass")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tollvehicleclass");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("tripid");

                    b.Property<string>("WaypointsJson")
                        .HasColumnType("text")
                        .HasColumnName("waypointsjson");

                    b.HasKey("RoutePlanId");

                    b.HasIndex("CorridorGeom")
                        .HasDatabaseName("ix_route_plans_corridorgeom_gist");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CorridorGeom"), "gist");

                    b.HasIndex("Geom")
                        .HasDatabaseName("ix_route_plans_geom_gist");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geom"), "gist");

                    b.HasIndex("TripId");

                    b.HasIndex("AccountId", "TripId")
                        .HasDatabaseName("ix_route_plans_accountid_tripid");

                    b.ToTable("route_plans", "trip");
                });

            modelBuilder.Entity("TrackHub.TripManagement.Infrastructure.TripDB.Entities.TollStation", b =>
                {
                    b.Property<Guid>("TollStationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<string>("Country")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Direction")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("direction");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("Operator")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("operator");

                    b.Property<Point>("Point")
                        .IsRequired()
                        .HasColumnType("geometry (Point, 4326)")
                        .HasColumnName("point");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("region");

                    b.Property<string>("RoadName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("roadname");

                    b.HasKey("TollStationId");

                    b.HasIndex("Point")
                        .HasDatabaseName("ix_toll_stations_point_gist");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Point"), "gist");

                    b.HasIndex(new[] { "Name", "Code" }, "toll_stations_name_code")
                        .IsUnique()
                        .HasDatabaseName("ux_toll_stations_name_code")
                        .HasFilter("code is not null");

                    b.HasIndex(new[] { "Name" }, "toll_stations_name_only")
                        .IsUnique()
                        .HasDatabaseName("ux_toll_stations_name_nocode")
                        .HasFilter("code is null");

                    b.ToTable("toll_stations", "trip");
                });

            modelBuilder.Entity("TrackHub.TripManagement.Infrastructure.TripDB.Entities.TollTariff", b =>
                {
                    b.Property<Guid>("TollTariffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effectivefrom");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effectiveto");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("TollStationId")
                        .HasColumnType("uuid")
                        .HasColumnName("tollstationid");

                    b.Property<string>("TollVehicleClassCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tollvehicleclasscode");

                    b.HasKey("TollTariffId");

                    b.HasIndex(new[] { "TollVehicleClassCode" }, "toll_tariffs_classcode_fk")
                        .HasDatabaseName("ix_toll_tariffs_tollvehicleclasscode");

                    b.HasIndex(new[] { "TollStationId", "TollVehicleClassCode" }, "toll_tariffs_lookup")
                        .HasDatabaseName("ix_toll_tariffs_tollstationid_classcode");

                    b.HasIndex(new[] { "TollStationId", "TollVehicleClassCode" }, "toll_tariffs_open")
                        .IsUnique()
                        .HasDatabaseName("ux_toll_tariffs_station_class_open")
                        .HasFilter("effectiveto is null");

                    b.ToTable("toll_tariffs", "trip");
                });

            modelBuilder.Entity("TrackHub.TripManagement.Infrastructure.TripDB.Entities.TollVehicleClass", b =>
                {
                    b.Property<Guid>("TollVehicleClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sortorder");

                    b.HasKey("TollVehicleClassId");

                    b.HasAlternateKey("Code")
                        .HasName("ux_toll_vehicle_classes_code");

                    b.ToTable("toll_vehicle_classes", "trip");
                });

            modelBuilder.Entity("TrackHub.TripManagement.Infrastructure.TripDB.Entities.Transporter", b =>
                {
                    b.Property<Guid>("TransporterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<short>("TransporterTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("transportertypeid");

                    b.HasKey("TransporterId");

                    b.ToTable("transporters", "app", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("TrackHub.TripManagement.Infrastructure.TripDB.Entities.TransporterTollClass", b =>
                {
                    b.Property<Guid>("TransporterTollClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("TollVehicleClassCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tollvehicleclasscode");

                    b.Property<Guid?>("TransporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("transporterid");

                    b.Property<short?>("TransporterTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("transportertypeid");

                    b.HasKey("TransporterTollClassId");

                    b.HasIndex(new[] { "TollVehicleClassCode" }, "transporter_toll_classes_classcode_fk")
                        .HasDatabaseName("ix_transporter_toll_classes_tollvehicleclasscode");

                    b.HasIndex(new[] { "AccountId", "TransporterId" }, "transporter_toll_classes_override")
                        .IsUnique()
                        .HasDatabaseName("ux_transporter_toll_classes_acct_transporter")
                        .HasFilter("transportertypeid is null");

                    b.HasIndex(new[] { "AccountId", "TransporterTypeId" }, "transporter_toll_classes_type")
                        .IsUnique()
                        .HasDatabaseName("ux_transporter_toll_classes_acct_type")
                        .HasFilter("transporterid is null");

                    b.ToTable("transporter_toll_classes", "trip", t =>
                        {
                            t.HasCheckConstraint("ck_transporter_toll_classes_type_xor_transporter", "(transportertypeid is null) <> (transporterid is null)");
                        });
                });

            modelBuilder.Entity("TrackHub.TripManagement.Infrastructure.TripDB.Entities.Trip", b =>
                {
                    b.Property<Guid>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<double>("ActualDistanceMeters")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("actualdistancemeters");

                    b.Property<DateTimeOffset?>("ActualEndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualendat");

                    b.Property<DateTimeOffset?>("ActualStartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualstartat");

                    b.Property<DateTimeOffset?>("ArmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("armedat");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancellationreason");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<int>("ConsecutiveOutsideFixes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("consecutiveoutsidefixes");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("customername");

                    b.Property<DateTimeOffset?>("DeviationOpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deviationopenedat");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driverid");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("externalreference");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Point>("LastPoint")
                        .HasColumnType("geometry (Point, 4326)")
                        .HasColumnName("lastpoint");

                    b.Property<DateTimeOffset?>("LastPositionAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastpositionat");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset?>("OriginArrivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("originarrivedat");

                    b.Property<DateTimeOffset?>("OriginDepartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("origindepartedat");

                    b.Property<Guid?>("OriginGeofenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("origingeofenceid");

                    b.Property<Polygon>("OriginGeom")
                        .HasColumnType("geometry (Polygon, 4326)")
                        .HasColumnName("origingeom");

                    b.Property<string>("OriginName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("originname");

                    b.Property<DateTimeOffset?>("OriginOutsideSinceAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("originoutsidesinceat");

                    b.Property<Point>("OriginPoint")
                        .IsRequired()
                        .HasColumnType("geometry (Point, 4326)")
                        .HasColumnName("originpoint");

                    b.Property<int>("OriginRadiusMeters")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(150)
                        .HasColumnName("originradiusmeters");

                    b.Property<DateTimeOffset?>("PlannedEndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("plannedendat");

                    b.Property<DateTimeOffset>("PlannedStartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("plannedstartat");

                    b.Property<Guid?>("RoutePlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("routeplanid");

                    b.Property<Guid?>("ServiceOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("serviceorderid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("TollVehicleClass")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tollvehicleclass");

                    b.Property<Guid>("TransporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("transporterid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("TripId");

                    b.HasIndex("OriginGeom")
                        .HasDatabaseName("ix_trips_origingeom_gist");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("OriginGeom"), "gist");

                    b.HasIndex("TransporterId")
                        .IsUnique()
                        .HasDatabaseName("ux_trips_transporterid_inprogress")
                        .HasFilter("status IN ('InProgress', 'Paused')");

                    b.HasIndex("AccountId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_trips_accountid_code");

                    b.HasIndex("AccountId", "ExternalReference")
                        .IsUnique()
                        .HasDatabaseName("ux_trips_accountid_externalreference")
                        .HasFilter("externalreference IS NOT NULL");

                    b.HasIndex("AccountId", "DriverId", "Status")
                        .HasDatabaseName("ix_trips_accountid_driverid_status");

                    b.HasIndex("AccountId", "Status", "PlannedStartAt")
                        .HasDatabaseName("ix_trips_accountid_status_plannedstartat");

                    b.HasIndex("AccountId", "TransporterId", "PlannedStartAt")
                        .HasDatabaseName("ix_trips_accountid_transporterid_plannedstartat");

                    b.ToTable("trips", "trip");
                });

            modelBuilder.Entity("TrackHub.TripManagement.Infrastructure.TripDB.Entities.TripAssignment", b =>
                {
                    b.Property<Guid>("TripAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledgedat");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assignedat");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driverid");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("endedat");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid>("TransporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("transporterid");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("tripid");

                    b.HasKey("TripAssignmentId");

                    b.HasIndex("TripId")
                        .IsUnique()
                        .HasDatabaseName("ux_trip_assignments_active_per_trip")
                        .HasFilter("status = 'Active'");

                    b.HasIndex("AccountId", "TripId")
                        .HasDatabaseName("ix_trip_assignments_accountid_tripid");

                    b.ToTable("trip_assignments", "trip");
                });

            modelBuilder.Entity("TrackHub.TripManagement.Infrastructure.TripDB.Entities.TripDocument", b =>
                {
                    b.Property<Guid>("TripDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("documentid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kind");

                    b.Property<Guid?>("ProofOfDeliveryId")
                        .HasColumnType("uuid")
                        .HasColumnName("proofofdeliveryid");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("tripid");

                    b.Property<Guid?>("TripStopId")
                        .HasColumnType("uuid")
                        .HasColumnName("tripstopid");

                    b.HasKey("TripDocumentId");

                    b.HasIndex("TripId", "DocumentId")
                        .IsUnique()
                        .HasDatabaseName("ux_trip_documents_tripid_documentid");

                    b.ToTable("trip_documents", "trip");
                });

            modelBuilder.Entity("TrackHub.TripManagement.Infrastructure.TripDB.Entities.TripEvent", b =>
                {
                    b.Property<Guid>("TripEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("eventtype");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotencykey");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurredat");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text")
                        .HasColumnName("payloadjson");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("source");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("tripid");

                    b.Property<Guid?>("TripStopId")
                        .HasColumnType("uuid")
                        .HasColumnName("tripstopid");

                    b.HasKey("TripEventId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_trip_events_idempotencykey");

                    b.HasIndex("TripId");

                    b.HasIndex("AccountId", "TripId", "OccurredAt")
                        .HasDatabaseName("ix_trip_events_accountid_tripid_occurredat");

                    b.ToTable("trip_events", "trip");
                });

            modelBuilder.Entity("TrackHub.TripManagement.Infrastructure.TripDB.Entities.TripShare", b =>
                {
                    b.Property<Guid>("TripShareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("CreatedByPrincipalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("createdbyprincipalid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiresat");

                    b.Property<bool>("IncludeDriverName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("includedrivername");

                    b.Property<bool>("IncludeLivePosition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("includeliveposition");

                    b.Property<bool>("IncludePodSummary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("includepodsummary");

                    b.Property<bool>("IncludeRoute")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("includeroute");

                    b.Property<bool>("IncludeStopDetail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("includestopdetail");

                    b.Property<bool>("IncludeVehicle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("includevehicle");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("PublicLinkGrantId")
                        .HasColumnType("uuid")
                        .HasColumnName("publiclinkgrantid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revokedat");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("tripid");

                    b.HasKey("TripShareId");

                    b.HasIndex("PublicLinkGrantId")
                        .IsUnique()
                        .HasDatabaseName("ux_trip_shares_publiclinkgrantid");

                    b.HasIndex("TripId");

                    b.HasIndex("AccountId", "TripId")
                        .HasDatabaseName("ix_trip_shares_accountid_tripid");

                    b.ToTable("trip_shares", "trip");
                });

            modelBuilder.Entity("TrackHub.TripManagement.Infrastructure.TripDB.Entities.TripStop", b =>
                {
                    b.Property<Guid>("TripStopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<string>("Activity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("Unload")
                        .HasColumnName("activity");

                    b.Property<DateTimeOffset?>("ActualArrivalAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualarrivalat");

                    b.Property<DateTimeOffset?>("ActualDepartureAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualdepartureat");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<Polygon>("ArrivalGeom")
                        .HasColumnType("geometry (Polygon, 4326)")
                        .HasColumnName("arrivalgeom");

                    b.Property<int>("ArrivalRadiusMeters")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(150)
                        .HasColumnName("arrivalradiusmeters");

                    b.Property<string>("City")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("city");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DelayAlertedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delayalertedat");

                    b.Property<DateTimeOffset?>("EtaAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("etaat");

                    b.Property<string>("EtaSource")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("etasource");

                    b.Property<Guid?>("GeofenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("geofenceid");

                    b.Property<DateTimeOffset>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Observations")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observations");

                    b.Property<DateTimeOffset?>("OutsideSinceAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("outsidesinceat");

                    b.Property<DateTimeOffset?>("PlannedArrivalFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("plannedarrivalfrom");

                    b.Property<DateTimeOffset?>("PlannedArrivalTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("plannedarrivalto");

                    b.Property<Point>("Point")
                        .IsRequired()
                        .HasColumnType("geometry (Point, 4326)")
                        .HasColumnName("point");

                    b.Property<short>("Priority")
                        .HasColumnType("smallint")
                        .HasColumnName("priority");

                    b.Property<bool>("RequiresPod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("requirespod");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("tripid");

                    b.HasKey("TripStopId");

                    b.HasIndex("ArrivalGeom")
                        .HasDatabaseName("ix_trip_stops_arrivalgeom_gist");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ArrivalGeom"), "gist");

                    b.HasIndex("AccountId", "TripId")
                        .HasDatabaseName("ix_trip_stops_accountid_tripid");

                    b.HasIndex("TripId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_trip_stops_tripid_sequence");

                    b.ToTable("trip_stops", "trip");
                });

            modelBuilder.Entity("TrackHub.TripManagement.Infrastructure.TripDB.Entities.VwUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.ToTable((string)null);

                    b.ToView("vw_users", "trip");
                });

            modelBuilder.Entity("TrackHub.TripManagement.Infrastructure.TripDB.Entities.VwVisibleTransporter", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountid");

                    b.Property<Guid>("TransporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("transporterid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.ToTable((string)null);

                    b.ToView("vw_visible_transporter", "trip");
                });

            modelBuilder.Entity("TrackHub.TripManagement.Infrastructure.TripDB.Entities.Delivery", b =>
                {
                    b.HasOne("TrackHub.TripManagement.Infrastructure.TripDB.Entities.TripStop", "TripStop")
                        .WithMany()
                        .HasForeignKey("TripStopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TripStop");
                });

            modelBuilder.Entity("TrackHub.TripManagement.Infrastructure.TripDB.Entities.ProofOfDelivery", b =>
                {
                    b.HasOne("TrackHub.TripManagement.Infrastructure.TripDB.Entities.TripStop", "TripStop")
                        .WithMany()
                        .HasForeignKey("TripStopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TripStop");
                });

            modelBuilder.Entity("TrackHub.TripManagement.Infrastructure.TripDB.Entities.RoutePlan", b =>
                {
                    b.HasOne("TrackHub.TripManagement.Infrastructure.TripDB.Entities.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TrackHub.TripManagement.Infrastructure.TripDB.Entities.TollTariff", b =>
                {
                    b.HasOne("TrackHub.TripManagement.Infrastructure.TripDB.Entities.TollStation", "TollStation")
                        .WithMany()
                        .HasForeignKey("TollStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrackHub.TripManagement.Infrastructure.TripDB.Entities.TollVehicleClass", null)
                        .WithMany()
                        .HasForeignKey("TollVehicleClassCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_toll_tariffs_tollvehicleclasscode");

                    b.Navigation("TollStation");
                });

            modelBuilder.Entity("TrackHub.TripManagement.Infrastructure.TripDB.Entities.TransporterTollClass", b =>
                {
                    b.HasOne("TrackHub.TripManagement.Infrastructure.TripDB.Entities.TollVehicleClass", null)
                        .WithMany()
                        .HasForeignKey("TollVehicleClassCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transporter_toll_classes_tollvehicleclasscode");
                });

            modelBuilder.Entity("TrackHub.TripManagement.Infrastructure.TripDB.Entities.TripAssignment", b =>
                {
                    b.HasOne("TrackHub.TripManagement.Infrastructure.TripDB.Entities.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TrackHub.TripManagement.Infrastructure.TripDB.Entities.TripDocument", b =>
                {
                    b.HasOne("TrackHub.TripManagement.Infrastructure.TripDB.Entities.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TrackHub.TripManagement.Infrastructure.TripDB.Entities.TripEvent", b =>
                {
                    b.HasOne("TrackHub.TripManagement.Infrastructure.TripDB.Entities.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TrackHub.TripManagement.Infrastructure.TripDB.Entities.TripShare", b =>
                {
                    b.HasOne("TrackHub.TripManagement.Infrastructure.TripDB.Entities.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TrackHub.TripManagement.Infrastructure.TripDB.Entities.TripStop", b =>
                {
                    b.HasOne("TrackHub.TripManagement.Infrastructure.TripDB.Entities.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });
#pragma warning restore 612, 618
        }
    }
}
